services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      platforms: ["linux/arm64"]
    image: lawtj/test-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      platforms: ["linux/arm64"]
    image: lawtj/test-backend
    ports:
      - "8727:8727"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=8727
    command: flask run --host=0.0.0.0 --port=8727

  pb:
    build:
      context: .
      dockerfile: Dockerfile.pb
    ports:
      - "8080:8080"
    volumes:
      - pb_migrations:/pb/pb_migrations
      - pb_hooks:/pb/pb_hooks
      - pb_data:/pb/pb_data
  
volumes:
  frontend_node_modules:
  pb_migrations:
  pb_hooks: 
  pb_data: