services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      platforms: ["linux/amd64"]
      args:
        - PUBLIC_API_CLIENT_URL
        - PUBLIC_PB_CLIENT_URL
    ports:
      - "3000:3000"
    command: node build

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      platforms: ["linux/amd64"]
    ports:
      - "8727:8727"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PORT=8727
    command: gunicorn --bind 0.0.0.0:8727 app:app 

  pb:
    build:
      context: .
      dockerfile: Dockerfile.pb
    ports:
      - "8081:8081"
    volumes:
      - pb_migrations:/pb/pb_migrations
      - pb_hooks:/pb/pb_hooks
      - pb_data:/pb/pb_data

volumes:
  pb_migrations:
  pb_hooks: 
  pb_data: