FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

EXPOSE 8727

CMD ["gunicorn", "--bind", "0.0.0.0:8727", "app:app"] 
