services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      platforms: ["linux/amd64", "linux/arm64"]
    image: lawtj/test-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://backend:8727
    # No volumes mounted in production
    command: node build

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      platforms: ["linux/amd64", "linux/arm64"]
    image: lawtj/test-backend
    ports:
      - "8727:8727"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PORT=8727
    command: gunicorn --bind 0.0.0.0:8727 app:app 